import React from 'react';
import { Box, Typography, Button, Skeleton } from '@mui/material';
import ReportProblemIcon from '@mui/icons-material/ReportProblem';
import InfoIcon from '@mui/icons-material/Info';
interface BaseProps { message:string; description?:string; actionLabel?:string; onAction?:()=>void; }
export const EmptyState:React.FC<BaseProps>=({message,description,actionLabel,onAction})=> (<Box role="status" aria-live="polite" sx={{ textAlign:'center', py:6, px:2 }}><InfoIcon color="primary" sx={{ fontSize:48, mb:1 }} /><Typography variant="h6" sx={{ mb:1 }}>{message}</Typography>{description && <Typography variant="body2" sx={{ color:'text.secondary', mb:2 }}>{description}</Typography>}{actionLabel && <Button variant="contained" onClick={onAction}>{actionLabel}</Button>}</Box>);
export const ErrorState:React.FC<BaseProps & { error?:any }>=({message,description,actionLabel,onAction,error})=> (<Box role="alert" aria-live="assertive" sx={{ textAlign:'center', py:6, px:2 }}><ReportProblemIcon color="error" sx={{ fontSize:48, mb:1 }} /><Typography variant="h6" sx={{ mb:1 }}>{message}</Typography>{description && <Typography variant="body2" sx={{ color:'text.secondary', mb:2 }}>{description}</Typography>}{error && <Typography variant="caption" sx={{ display:'block', color:'error.main', mb:2 }}>{String(error)}</Typography>}{actionLabel && <Button variant="outlined" color="error" onClick={onAction}>{actionLabel}</Button>}</Box>);
export const LoadingState:React.FC<{lines?:number}>=({lines=3})=> (<Box role="status" aria-live="polite" sx={{ py:2 }}>{[...Array(lines)].map((_,i)=>(<Skeleton key={i} variant="rectangular" height={32} sx={{ mb:1, borderRadius:1 }} />))}</Box>);
export const SkeletonPanel:React.FC<{rows?:number;heading?:boolean}>=({rows=6,heading=true})=> (<Box sx={{ p:2 }}>{heading && <Skeleton variant="text" width={180} sx={{ mb:2 }} />}{[...Array(rows)].map((_,i)=>(<Skeleton key={i} variant="rectangular" height={28} sx={{ mb:1.2, borderRadius:0.75 }} />))}</Box>);
