// Moved copy (will be relocated) - placeholder to keep history
import React, { useMemo, useState } from 'react';
import { Box, List, ListItemButton, ListItemIcon, ListItemText, Collapse, Chip, Tooltip, IconButton } from '@mui/material';
import DashboardIcon from '@mui/icons-material/Dashboard';
import SettingsIcon from '@mui/icons-material/Settings';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import MenuIcon from '@mui/icons-material/Menu';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import { tokens } from '../../design/tokens';
import { animation, prefersReducedMotion } from '../../design/animation';
export interface UnifiedSidebarProps { selected:string; onSelect:(id:string)=>void; variant?:'legacy'|'modern'|'auto'; menuConfig?: Array<{ id:string; label:string; icon?:React.ElementType; group?:string; badge?:string; roles?:string[]; featureFlag?:string }>; }
const baseMenu: UnifiedSidebarProps['menuConfig'] = [ { id:'dashboard', label:'Dashboard', icon:DashboardIcon, group:'core' }, { id:'settings', label:'Settings', icon:SettingsIcon, group:'standard' }, { id:'holographic-ui', label:'Holographic UI', icon:AutoAwesomeIcon, group:'revolutionary', badge:'REV' } ];
const groupOrder=['core','revolutionary','standard'];
const UnifiedSidebar:React.FC<UnifiedSidebarProps>=({ selected,onSelect,variant='auto',menuConfig })=>{ const [collapsed,setCollapsed]=useState(false); const [openGroups,setOpen]=useState<Record<string,boolean>>({ core:true, revolutionary:true, standard:true }); const items=menuConfig?.length? menuConfig: baseMenu; const grouped=useMemo(()=>{ const map:Record<string,typeof items>={}; items.forEach(i=>{ const g=i.group||'other'; if(!map[g]) map[g]=[]; map[g].push(i); }); return map; },[items]); const toggleGroup=(g:string)=> setOpen(o=>({ ...o, [g]: !o[g] })); return (<Box component="nav" role="navigation" aria-label="Primary" sx={{ width: collapsed? tokens.layout.sidebarCollapsed: tokens.layout.sidebarWidth, backgroundColor:'#1a1a1a', color:'#fff', borderRight:'1px solid #333', display:'flex', flexDirection:'column', transition: prefersReducedMotion()? 'none' : `width ${animation.durations.normal}ms ${animation.easing.standard}` }}><Box sx={{ display:'flex', alignItems:'center', justifyContent: collapsed? 'center':'space-between', px:2, py:1.5, borderBottom:'1px solid #333' }}>{!collapsed && <Box sx={{ fontWeight:700, fontSize:'0.95rem', background:'linear-gradient(45deg,#00d4ff,#ff6b35)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent' }}>PROMETHEUS</Box>}<Tooltip title={collapsed? 'Expand sidebar':'Collapse sidebar'}><IconButton size="small" onClick={()=>setCollapsed(c=>!c)} sx={{ color:'#00d4ff' }} aria-label="Toggle sidebar">{collapsed? <MenuIcon />:<ChevronLeftIcon />}</IconButton></Tooltip></Box><Box sx={{ flex:1, overflow:'auto' }}>{groupOrder.filter(g=> grouped[g]).map(g=>(<Box key={g} sx={{ mt:1 }}><ListItemButton onClick={()=>toggleGroup(g)} sx={{ py:0.75, opacity: collapsed?0:1 }} aria-expanded={openGroups[g]} aria-controls={`group-${g}`}><ListItemText primary={g.toUpperCase()} primaryTypographyProps={{ variant:'overline', sx:{ letterSpacing:1, color:'#888' } }} /></ListItemButton><Collapse in={openGroups[g]} timeout={prefersReducedMotion()? 0: animation.durations.normal} unmountOnExit><List disablePadding id={`group-${g}`}>{grouped[g].map(item=>{ const Icon=item.icon||DashboardIcon; const sel= selected===item.id; return (<ListItemButton key={item.id} selected={sel} onClick={()=>onSelect(item.id)} sx={{ pl: collapsed?1:3, '&.Mui-selected':{ backgroundColor:'#272727' } }} aria-current={sel? 'page': undefined}><ListItemIcon sx={{ minWidth: collapsed?40:48, color: sel? '#00d4ff':'#888' }}><Icon /></ListItemIcon>{!collapsed && <ListItemText primary={<>{item.label}{item.badge && <Chip size="small" label={item.badge} sx={{ ml:1, height:18, fontSize:'0.6rem' }} />}</>} />}</ListItemButton>); })}</List></Collapse></Box>))}</Box><Box component="footer" role="contentinfo" sx={{ p:1.5, fontSize:12, color:'#777', textAlign: collapsed? 'center':'left' }}>v1 • Status: Online</Box></Box>); };
export default UnifiedSidebar;
